---
name: ExamplesOS-ostree
steps:
  - step: bootstrap
    options:
      suite: bookworm
      target: rootfs.tar.gz
      setup-hooks:
        - 'sync-in overlay/debian/ /'
      customize-hooks:
        - echo 'root:root' | chroot "$1" chpasswd
        - systemctl enable --root="$1" systemd-networkd
        - chroot $1 echo "localhost" > $1/etc/hostname
        - mkdir -p $1/efi
      packages: !include manifests/software.yaml
  - step: ostree_init
    options:
      repo: /var/www/html/repo
      mode: archive-z2
  - step: ostree_prep
    options:
      repo: /var/www/html/repo
      branch: exampleos/testing
      target: rootfs.tar.gz
  - step: image
    options:
      image:
        name: disk.img
        size: 10G
        label: gpt
      partitions:
        - name: EFI
          start: 0%
          end: 256MB
          type: "c12a7328-f81f-11d2-ba4b-00a0c93ec93b"
          flags: [boot, esp]
        - name: ROOT
          start: 256MB
          end: 100%
          type: "4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709"
      filesystems:
        - name: EFI
          label: EFI
          fs: vfat
          options: []
        - name: ROOT
          label: ROOT
          fs: ext4
          options: []
  - step: ostree_deploy
    options:
      repo: /var/www/html/repo
      branch: exampleos/testing
      image: disk.img
      kernel_args:
        - root=LABEL=ROOT
        - rw
        - console=tty0
        - console=ttyS0,115200n8
